### ISSUE TITLE
Weekly Checklist

### ISSUE THREAD

**Issue by SamGJohn** [SamGJohn/CircleCI-Agile#434]
- [ ] Create List of 5 guest blog publications (1)
- [ ] Reach out to 1 publication about letting us guest blog (1)
- [ ] 2hr quality score optimization (4)
- [x] 1 Adwords MVT (1)
- [ ] 1 Google Remarketing MVT (1)
- [x] 1 Quora MVT (1)
- [x] 1 Adroll MVT (1)
- [ ] 1 Perfect Audience MVT (1)
- [x] 1 Reddit MVT (1)
- [x] Demand Gen Slides (4)

**Comment by SamGJohn** [comment]
Signup MVT - Increased Display Signup budget & Changed to CPA campaign
MQL MVT - Increased budget on Search Enterprise Branded campaign

**Comment by SamGJohn** [comment]
Added quora remarketing campaign

**Comment by SamGJohn** [comment]
Launched Reddit ad for Android Devs
